<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>Separador_de_Listas_de_Planejadores</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>PDF_PDFS.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="PDF_PDFS.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="itext7" Version="9.5.0" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="9.5.0" />
  </ItemGroup>

</Project>